name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Build 
      run: go build .
      
    - name: Test code
      run: go test .
    
    - name: Run
      run: go run hello.go
      
  Docker-Lint:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: go-test
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./Dockerfile
      
  Docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: Docker-Lint
    steps:
    - name: Update tag to GIT_SHA env property with commit short sha
      run: echo "GIT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      id: version
     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Docker lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: build local container
      uses: docker/build-push-action@v2
      id: build
      with:
        tags: localbuild/goimage:${{ env.GIT_SHA }}
        push: false
        load: true  
        
  Docker-scan:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/master'
   needs: Docker-build
   steps:
    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "localbuild/goimage:${{ env.GIT_SHA }}"
        acs-report-enable: true
        severity-cutoff: critical
        fail-build: false
        debug: true
    
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
