name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Build 
      run: go build .
      working-directory: "demo/"

    - name: Test code
      run: go test .
      working-directory: "demo/"
    
    #- name: Run
    #  run: go run main.go
    #  working-directory: "demo/"
      
  Docker-Lint:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: go-test
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: "./demo/Dockerfile" 
  Docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: Docker-Lint
    permissions:
      contents: 'read'
      id-token: 'write'
    #env:
    #  IMAGE_NAME: gcr.io/ingka-apim-global-dev/go-code
    steps:
    - name: Update tag to GIT_SHA env property with commit short sha
      run: echo "GIT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      id: version
    
    - name: Build and tag Docker Image
      run: docker build -t $IMAGE_NAME:${{ env.GIT_SHA }}  .
      working-directory: demo/
        
    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "gcr.io/ingka-apim-global-dev/go-code:${{ env.GIT_SHA }}"
        acs-report-enable: true
        severity-cutoff: critical
        fail-build: false
        debug: true
    
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
########################----------Cloud Run Configuration------------------############################### 
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{secrets.WIP_PROVIDER}}
        service_account: ${{secrets.WIP_SA}}
                     
    - name: Configure Docker Authentication
      run: gcloud auth configure-docker --quiet

    - name: Push Docker image to GCR
      run: docker push gcr.io/ingka-apim-global-dev/go-code:${{ env.GIT_SHA }}

    - name: Deploy go code to cloud run
      id: deploy
      run: gcloud run deploy rest-api --image gcr.io/ingka-apim-global-dev/go-code:${{ env.GIT_SHA }} --platform managed --region us-central1  --allow-unauthenticated --max-instances=1 --port=8000
########################----------Cloud Run Configuration------------------############################### 
