name: Go

on:
  push:
    branches: [ abcd ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Build 
      run: go build -v hello.go
      working-directory: "hello/"
    
    - name: Run
      run: go run hello.go
      working-directory: "hello/"
