name: "Go for prod deployment"

on:
  workflow_dispatch:
    inputs:
      skip_build_n_override_tag:
        description: 'Set to True if required to skip the build and set the Stage deployment to a specific tag & pass the tag value to input - tag_to_override'
        required: false
        default: 'false'
      tag_to_override:
        description: 'If needed to skip the build, Pass the tag value to override & set the input - skip_build_n_override_tag to true'
        required: false
  push:
      tags:
        - "v*"

  jobs:
  Docker-build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    #env:
    #  IMAGE_NAME: gcr.io/ingka-apim-global-dev/go-code
    steps:
    - uses: actions/checkout@v2
    
    - name: Update tag to GIT_SHA env property with commit short sha
      run: echo "GIT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      id: version
      
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{secrets.WIP_PROVIDER}}
        service_account: ${{secrets.WIP_SA}}
                     
    - name: Configure Docker Authentication
      run: gcloud auth configure-docker --quiet
    
    - name: Build and tag Docker Image
      run: docker build -t gcr.io/ingka-apim-global-dev/go-code:${{ env.GIT_SHA }} .
        
    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "gcr.io/ingka-apim-global-dev/go-code:${{ env.GIT_SHA }}"
        acs-report-enable: true
        severity-cutoff: critical
        fail-build: false
        debug: true
    
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
      
    - name: Push Docker image to GCR
      run: docker push gcr.io/ingka-apim-global-dev/go-code:${{ env.GIT_SHA }}
########################----------Cloud Run Configuration------------------############################### 
    - name: Deploy go code to cloud run
      id: deploy
      run: gcloud run deploy rest-api --image gcr.io/ingka-apim-global-dev/go-code:${{ env.GIT_SHA }} --platform managed --region europe-west4  --allow-unauthenticated --max-instances=1 --port=8000  --ingress=internal --timeout=30 --concurrency=80 --vpc-connector=projects/ingka-apim-global-dev/locations/europe-west4/connectors/kong-gw-cloudrun
########################----------Cloud Run Configuration------------------############################### 
